<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Array of products for each category
        $products = [
            // Category 1: 處理器 CPU
            1 => [
                [
                    'product_name' => 'Intel Core i9-13900K',
                    'product_price' => 9999,
                    'product_description' => 'Intel Core i9-13900K 處理器，13代酷睿系列，適合高效能運算。',
                    'supplier_id' => 4,
                    'launch_date' => Carbon::create(2022, 10, 20),
                    'product_image' => 'CPU13900K1',
                ],
                [
                    'product_name' => 'Intel Core i7-13700K',
                    'product_price' => 7999,
                    'product_description' => 'Intel Core i7-13700K 處理器，高效能遊戲與工作站首選。',
                    'supplier_id' => 4,
                    'launch_date' => Carbon::create(2022, 10, 20),
                    'product_image' => 'CPU13700K1',
                ],
                [
                    'product_name' => 'AMD Ryzen 9 7950X',
                    'product_price' => 10999,
                    'product_description' => 'AMD Ryzen 9 7950X，16核心高效能處理器，支援Zen 4架構。',
                    'supplier_id' => 5,
                    'launch_date' => Carbon::create(2022, 9, 27),
                    'product_image' => 'CPU7950X01',
                ],
                [
                    'product_name' => 'AMD Ryzen 7 7700X',
                    'product_price' => 6999,
                    'product_description' => 'AMD Ryzen 7 7700X，8核心高效能，適合遊戲與創作。',
                    'supplier_id' => 5,
                    'launch_date' => Carbon::create(2022, 9, 27),
                    'product_image' => 'CPU7700X01',
                ],
                [
                    'product_name' => 'Intel Core i5-13600K',
                    'product_price' => 5999,
                    'product_description' => 'Intel Core i5-13600K，中階高效能處理器，性價比優異。',
                    'supplier_id' => 4,
                    'launch_date' => Carbon::create(2022, 10, 20),
                    'product_image' => 'CPU13600K1',
                ],
                [
                    'product_name' => 'AMD Ryzen 5 7600X',
                    'product_price' => 4999,
                    'product_description' => 'AMD Ryzen 5 7600X，6核心處理器，適合主流遊戲玩家。',
                    'supplier_id' => 5,
                    'launch_date' => Carbon::create(2022, 9, 27),
                    'product_image' => 'CPU7600X01',
                ],
                [
                    'product_name' => 'Intel Core i9-12900K',
                    'product_price' => 8999,
                    'product_description' => 'Intel Core i9-12900K，12代旗艦處理器，高效能運算。',
                    'supplier_id' => 4,
                    'launch_date' => Carbon::create(2021, 11, 4),
                    'product_image' => 'CPU12900K1',
                ],
                [
                    'product_name' => 'AMD Ryzen 9 5950X',
                    'product_price' => 9999,
                    'product_description' => 'AMD Ryzen 9 5950X，16核心，適合專業創作與運算。',
                    'supplier_id' => 5,
                    'launch_date' => Carbon::create(2020, 11, 5),
                    'product_image' => 'CPU5950X01',
                ],
                [
                    'product_name' => 'Intel Core i3-13100',
                    'product_price' => 2999,
                    'product_description' => 'Intel Core i3-13100，入門級處理器，適合基本應用。',
                    'supplier_id' => 4,
                    'launch_date' => Carbon::create(2023, 1, 3),
                    'product_image' => 'CPU13100I3',
                ],
                [
                    'product_name' => 'AMD Ryzen 3 5300G',
                    'product_price' => 2499,
                    'product_description' => 'AMD Ryzen 3 5300G，內建顯示，適合輕量級遊戲與辦公。',
                    'supplier_id' => 5,
                    'launch_date' => Carbon::create(2021, 4, 13),
                    'product_image' => 'CPU5300G01',
                ],
            ],
            // Category 2: 主機板 MB
            2 => [
                [
                    'product_name' => 'ASUS ROG Strix Z790-E Gaming',
                    'product_price' => 7999,
                    'product_description' => 'ASUS ROG Strix Z790-E Gaming 主機板，支援13代Intel CPU。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2022, 10, 20),
                    'product_image' => 'MBZ790E001',
                ],
                [
                    'product_name' => 'MSI MPG Z790 Carbon WiFi',
                    'product_price' => 7499,
                    'product_description' => 'MSI MPG Z790 Carbon WiFi，高效能主機板，支援WiFi 6E。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2022, 10, 20),
                    'product_image' => 'MBZ790C001',
                ],
                [
                    'product_name' => 'GIGABYTE Z790 AORUS Elite AX',
                    'product_price' => 6999,
                    'product_description' => 'GIGABYTE Z790 AORUS Elite AX，支援DDR5與PCIe 5.0。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2022, 10, 20),
                    'product_image' => 'MBZ790A001',
                ],
                [
                    'product_name' => 'ASUS TUF Gaming B550-PLUS',
                    'product_price' => 3999,
                    'product_description' => 'ASUS TUF Gaming B550-PLUS，支援AMD Ryzen 5000系列。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 10, 8),
                    'product_image' => 'MBB550P001',
                ],
                [
                    'product_name' => 'MSI B550 Tomahawk',
                    'product_price' => 3499,
                    'product_description' => 'MSI B550 Tomahawk，穩定耐用，適合中階玩家。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2020, 10, 8),
                    'product_image' => 'MBB550T001',
                ],
                [
                    'product_name' => 'GIGABYTE B550 AORUS Pro',
                    'product_price' => 3799,
                    'product_description' => 'GIGABYTE B550 AORUS Pro，支援高效能AMD CPU。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2020, 10, 8),
                    'product_image' => 'MBB550A001',
                ],
                [
                    'product_name' => 'ASUS Prime Z690-P',
                    'product_price' => 4999,
                    'product_description' => 'ASUS Prime Z690-P，支援12代Intel CPU，性價比高。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2021, 11, 4),
                    'product_image' => 'MBZ690P001',
                ],
                [
                    'product_name' => 'MSI Z690-A Pro',
                    'product_price' => 4599,
                    'product_description' => 'MSI Z690-A Pro，穩定高效，適合專業與遊戲用途。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2021, 11, 4),
                    'product_image' => 'MBZ690A001',
                ],
                [
                    'product_name' => 'GIGABYTE Z690 Gaming X',
                    'product_price' => 4799,
                    'product_description' => 'GIGABYTE Z690 Gaming X，支援DDR5，適合高效能組裝。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2021, 11, 4),
                    'product_image' => 'MBZ690G001',
                ],
                [
                    'product_name' => 'ASUS ROG Maximus Z790 Hero',
                    'product_price' => 9999,
                    'product_description' => 'ASUS ROG Maximus Z790 Hero，頂級主機板，支援極致超頻。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2022, 10, 20),
                    'product_image' => 'MBZ790H001',
                ],
            ],
            // Category 3: 記憶體 RAM
            3 => [
                [
                    'product_name' => 'Kingston Fury Beast 16GB DDR5',
                    'product_price' => 2499,
                    'product_description' => 'Kingston Fury Beast 16GB DDR5，5200MHz高效能記憶體。',
                    'supplier_id' => 7,
                    'launch_date' => Carbon::create(2022, 11, 1),
                    'product_image' => 'RAM16GB501',
                ],
                [
                    'product_name' => 'Micron Crucial 32GB DDR5',
                    'product_price' => 3999,
                    'product_description' => 'Micron Crucial 32GB DDR5，5600MHz，適合專業應用。',
                    'supplier_id' => 6,
                    'launch_date' => Carbon::create(2022, 11, 1),
                    'product_image' => 'RAM32GB501',
                ],
                [
                    'product_name' => 'Team Group T-Force 16GB DDR4',
                    'product_price' => 1699,
                    'product_description' => 'Team Group T-Force 16GB DDR4，3600MHz，遊戲專用記憶體。',
                    'supplier_id' => 9,
                    'launch_date' => Carbon::create(2021, 6, 15),
                    'product_image' => 'RAM16GB401',
                ],
                [
                    'product_name' => 'ADATA XPG 32GB DDR4',
                    'product_price' => 2799,
                    'product_description' => 'ADATA XPG 32GB DDR4，3200MHz，高效能與穩定性兼具。',
                    'supplier_id' => 10,
                    'launch_date' => Carbon::create(2021, 6, 15),
                    'product_image' => 'RAM32GB401',
                ],
                [
                    'product_name' => 'Kingmax Zeus 16GB DDR4',
                    'product_price' => 1599,
                    'product_description' => 'Kingmax Zeus 16GB DDR4，3000MHz，入門級高效記憶體。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2020, 8, 20),
                    'product_image' => 'RAM16GB402',
                ],
                [
                    'product_name' => 'Kingston Fury Renegade 64GB DDR5',
                    'product_price' => 7999,
                    'product_description' => 'Kingston Fury Renegade 64GB DDR5，6000MHz，頂級效能。',
                    'supplier_id' => 7,
                    'launch_date' => Carbon::create(2023, 2, 10),
                    'product_image' => 'RAM64GB501',
                ],
                [
                    'product_name' => 'Micron Ballistix 16GB DDR4',
                    'product_price' => 1799,
                    'product_description' => 'Micron Ballistix 16GB DDR4，3600MHz，適合遊戲與超頻。',
                    'supplier_id' => 6,
                    'launch_date' => Carbon::create(2020, 10, 1),
                    'product_image' => 'RAM16GB403',
                ],
                [
                    'product_name' => 'Team Group Elite 8GB DDR4',
                    'product_price' => 999,
                    'product_description' => 'Team Group Elite 8GB DDR4，2666MHz，經濟型記憶體。',
                    'supplier_id' => 9,
                    'launch_date' => Carbon::create(2020, 5, 10),
                    'product_image' => 'RAM08GB401',
                ],
                [
                    'product_name' => 'ADATA Premier 16GB DDR5',
                    'product_price' => 2299,
                    'product_description' => 'ADATA Premier 16GB DDR5，4800MHz，穩定高效能。',
                    'supplier_id' => 10,
                    'launch_date' => Carbon::create(2022, 12, 1),
                    'product_image' => 'RAM16GB502',
                ],
                [
                    'product_name' => 'Kingmax 32GB DDR4',
                    'product_price' => 2699,
                    'product_description' => 'Kingmax 32GB DDR4，3200MHz，適合多任務處理。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2021, 7, 15),
                    'product_image' => 'RAM32GB402',
                ],
            ],
            // Category 4: 固態硬碟 SSD
            4 => [
                [
                    'product_name' => 'Micron Crucial MX500 1TB',
                    'product_price' => 2499,
                    'product_description' => 'Micron Crucial MX500 1TB SATA SSD，高速穩定。',
                    'supplier_id' => 6,
                    'launch_date' => Carbon::create(2020, 1, 10),
                    'product_image' => 'SSD1TB0001',
                ],
                [
                    'product_name' => 'Kingston NV2 2TB NVMe',
                    'product_price' => 3999,
                    'product_description' => 'Kingston NV2 2TB NVMe SSD，PCIe 4.0高速傳輸。',
                    'supplier_id' => 7,
                    'launch_date' => Carbon::create(2022, 3, 15),
                    'product_image' => 'SSD2TB0001',
                ],
                [
                    'product_name' => 'ADATA XPG SX8200 Pro 1TB',
                    'product_price' => 2799,
                    'product_description' => 'ADATA XPG SX8200 Pro 1TB，高效能NVMe SSD。',
                    'supplier_id' => 10,
                    'launch_date' => Carbon::create(2021, 5, 20),
                    'product_image' => 'SSD1TB0002',
                ],
                [
                    'product_name' => 'Team Group MP34 512GB',
                    'product_price' => 1499,
                    'product_description' => 'Team Group MP34 512GB NVMe SSD，性價比高。',
                    'supplier_id' => 9,
                    'launch_date' => Carbon::create(2020, 8, 10),
                    'product_image' => 'SSD512GB01',
                ],
                [
                    'product_name' => 'Kingmax PX4480 1TB',
                    'product_price' => 2599,
                    'product_description' => 'Kingmax PX4480 1TB NVMe SSD，高速讀寫。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2022, 6, 1),
                    'product_image' => 'SSD1TB0003',
                ],
                [
                    'product_name' => 'Micron Crucial P3 Plus 2TB',
                    'product_price' => 4299,
                    'product_description' => 'Micron Crucial P3 Plus 2TB，PCIe 4.0高效能SSD。',
                    'supplier_id' => 6,
                    'launch_date' => Carbon::create(2022, 7, 15),
                    'product_image' => 'SSD2TB0002',
                ],
                [
                    'product_name' => 'Kingston A2000 1TB',
                    'product_price' => 2399,
                    'product_description' => 'Kingston A2000 1TB NVMe SSD，穩定耐用。',
                    'supplier_id' => 7,
                    'launch_date' => Carbon::create(2020, 5, 1),
                    'product_image' => 'SSD1TB0004',
                ],
                [
                    'product_name' => 'ADATA SU800 512GB',
                    'product_price' => 1399,
                    'product_description' => 'ADATA SU800 512GB SATA SSD，經濟型選擇。',
                    'supplier_id' => 10,
                    'launch_date' => Carbon::create(2019, 10, 10),
                    'product_image' => 'SSD512GB02',
                ],
                [
                    'product_name' => 'Team Group T-Force 1TB',
                    'product_price' => 2699,
                    'product_description' => 'Team Group T-Force 1TB NVMe SSD，遊戲專用。',
                    'supplier_id' => 9,
                    'launch_date' => Carbon::create(2021, 9, 1),
                    'product_image' => 'SSD1TB0005',
                ],
                [
                    'product_name' => 'Kingmax M.2 2280 2TB',
                    'product_price' => 4199,
                    'product_description' => 'Kingmax M.2 2280 2TB SSD，高速大容量。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2023, 1, 20),
                    'product_image' => 'SSD2TB0003',
                ],
            ],
            // Category 5: 傳統硬碟 HDD
            5 => [
                [
                    'product_name' => 'Western Digital 4TB 7200RPM',
                    'product_price' => 2999,
                    'product_description' => 'Western Digital 4TB 7200RPM HDD，大容量儲存解決方案，適用於桌上型電腦與高效能需求。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2021, 3, 10),
                    'product_image' => 'HDD4TB0001',
                ],
                [
                    'product_name' => 'Western Digital 8TB 7200RPM',
                    'product_price' => 4999,
                    'product_description' => 'Western Digital 8TB 7200RPM HDD，適合NAS與伺服器，支援高負載工作環境。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2022, 1, 15),
                    'product_image' => 'HDD8TB0001',
                ],
                [
                    'product_name' => 'Western Digital 2TB 5400RPM',
                    'product_price' => 1799,
                    'product_description' => 'Western Digital 2TB 5400RPM HDD，經濟型儲存選擇，低功耗設計。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2020, 6, 1),
                    'product_image' => 'HDD2TB0001',
                ],
                [
                    'product_name' => 'Western Digital 6TB 7200RPM',
                    'product_price' => 3999,
                    'product_description' => 'Western Digital 6TB 7200RPM HDD，高效能大容量儲存，適合專業應用。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2021, 8, 20),
                    'product_image' => 'HDD6TB0001',
                ],
                [
                    'product_name' => 'Western Digital 1TB 7200RPM',
                    'product_price' => 1299,
                    'product_description' => 'Western Digital 1TB 7200RPM HDD，入門級硬碟，適合基本儲存需求。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2019, 12, 1),
                    'product_image' => 'HDD1TB0001',
                ],
                [
                    'product_name' => 'Western Digital 10TB 7200RPM',
                    'product_price' => 5999,
                    'product_description' => 'Western Digital 10TB 7200RPM HDD，超大容量企業級儲存，適合數據中心。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2022, 5, 10),
                    'product_image' => 'HDD10TB001',
                ],
                [
                    'product_name' => 'Western Digital 3TB 5400RPM',
                    'product_price' => 2199,
                    'product_description' => 'Western Digital 3TB 5400RPM HDD，適合家庭儲存，低噪音設計。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2020, 9, 15),
                    'product_image' => 'HDD3TB0001',
                ],
                [
                    'product_name' => 'Western Digital 12TB 7200RPM',
                    'product_price' => 6999,
                    'product_description' => 'Western Digital 12TB 7200RPM HDD，專業級大容量儲存，適合NAS與伺服器。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2023, 3, 1),
                    'product_image' => 'HDD12TB001',
                ],
                [
                    'product_name' => 'Western Digital 5TB 5400RPM',
                    'product_price' => 3499,
                    'product_description' => 'Western Digital 5TB 5400RPM HDD，穩定耐用儲存方案，適合長期備份。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2021, 11, 20),
                    'product_image' => 'HDD5TB0001',
                ],
                [
                    'product_name' => 'Western Digital 16TB 7200RPM',
                    'product_price' => 7999,
                    'product_description' => 'Western Digital 16TB 7200RPM HDD，極致容量企業儲存，適合高負載應用。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2023, 6, 1),
                    'product_image' => 'HDD16TB001',
                ],
                // 新增的 Western Digital 硬碟（product_image 調整為 10 字元）
                [
                    'product_name' => 'Western Digital WD Red Plus 8TB 5640RPM',
                    'product_price' => 6980,
                    'product_description' => 'Western Digital WD Red Plus 8TB 5640RPM HDD，專為NAS設計，支援24/7運行，256MB快取。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2023, 1, 1),
                    'product_image' => 'HDD8TB0002',
                ],
                [
                    'product_name' => 'Western Digital WD Blue 4TB 5400RPM',
                    'product_price' => 2980,
                    'product_description' => 'Western Digital WD Blue 4TB 5400RPM HDD，適合桌機與日常儲存，低功耗高效能。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2022, 7, 1),
                    'product_image' => 'HDD4TB0002',
                ],
                [
                    'product_name' => 'Western Digital WD Gold 18TB 7200RPM',
                    'product_price' => 12800,
                    'product_description' => 'Western Digital WD Gold 18TB 7200RPM HDD，企業級硬碟，適合數據中心與高可靠性需求。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2023, 9, 1),
                    'product_image' => 'HDD18TB001',
                ],
                [
                    'product_name' => 'Western Digital WD Black 6TB 7200RPM',
                    'product_price' => 5280,
                    'product_description' => 'Western Digital WD Black 6TB 7200RPM HDD，高效能硬碟，適合遊戲與創作者使用。',
                    'supplier_id' => 11,
                    'launch_date' => Carbon::create(2022, 10, 1),
                    'product_image' => 'HDD6TB0002',
                ],
            ],
            // Category 6: 顯示卡 VGA
            6 => [
                [
                    'product_name' => 'ASUS ROG Strix RTX 4090',
                    'product_price' => 29999,
                    'product_description' => 'ASUS ROG Strix RTX 4090，頂級遊戲顯示卡，支援DLSS 3。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2022, 10, 12),
                    'product_image' => 'VGA4090A01',
                ],
                [
                    'product_name' => 'MSI GeForce RTX 4080 Gaming X',
                    'product_price' => 24999,
                    'product_description' => 'MSI GeForce RTX 4080 Gaming X，高效能遊戲顯示卡。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2022, 11, 16),
                    'product_image' => 'VGA4080M01',
                ],
                [
                    'product_name' => 'GIGABYTE RTX 4070 Ti Eagle',
                    'product_price' => 18999,
                    'product_description' => 'GIGABYTE RTX 4070 Ti Eagle，高性價比4K遊戲顯示卡。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2023, 1, 5),
                    'product_image' => 'VGA4070G01',
                ],
                [
                    'product_name' => 'ASUS TUF Gaming RTX 3080',
                    'product_price' => 15999,
                    'product_description' => 'ASUS TUF Gaming RTX 3080，穩定高效能遊戲卡。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 9, 17),
                    'product_image' => 'VGA3080A01',
                ],
                [
                    'product_name' => 'MSI Radeon RX 7900 XTX',
                    'product_price' => 21999,
                    'product_description' => 'MSI Radeon RX 7900 XTX，AMD旗艦級顯示卡。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2022, 12, 13),
                    'product_image' => 'VGA7900M01',
                ],
                [
                    'product_name' => 'GIGABYTE Radeon RX 6800 XT',
                    'product_price' => 13999,
                    'product_description' => 'GIGABYTE Radeon RX 6800 XT，高效能AMD顯示卡。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2020, 11, 18),
                    'product_image' => 'VGA6800G01',
                ],
                [
                    'product_name' => 'ASUS Dual RTX 3060',
                    'product_price' => 7999,
                    'product_description' => 'ASUS Dual RTX 3060，中階遊戲顯示卡，性價比高。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2021, 2, 25),
                    'product_image' => 'VGA3060A01',
                ],
                [
                    'product_name' => 'MSI GeForce GTX 1660 Super',
                    'product_price' => 4999,
                    'product_description' => 'MSI GeForce GTX 1660 Super，入門級1080p遊戲卡。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2019, 10, 29),
                    'product_image' => 'VGA1660M01',
                ],
                [
                    'product_name' => 'GIGABYTE RTX 3050 Eagle',
                    'product_price' => 5999,
                    'product_description' => 'GIGABYTE RTX 3050 Eagle，經濟型遊戲顯示卡。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2022, 1, 27),
                    'product_image' => 'VGA3050G01',
                ],
                [
                    'product_name' => 'ASUS ROG Strix RX 7600',
                    'product_price' => 6999,
                    'product_description' => 'ASUS ROG Strix RX 7600，AMD中階遊戲顯示卡。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2023, 5, 25),
                    'product_image' => 'VGA7600A01',
                ],
            ],
            // Category 7: 電源供應 PSU
            7 => [
                [
                    'product_name' => 'ASUS ROG Thor 1200W Platinum',
                    'product_price' => 7999,
                    'product_description' => 'ASUS ROG Thor 1200W Platinum，80+ Platinum認證電源。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2021, 10, 1),
                    'product_image' => 'PSU1200A01',
                ],
                [
                    'product_name' => 'MSI MPG A850G PCIE5',
                    'product_price' => 3999,
                    'product_description' => 'MSI MPG A850G PCIE5，80+ Gold高效電源。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2022, 9, 15),
                    'product_image' => 'PSU0850M01',
                ],
                [
                    'product_name' => 'GIGABYTE UD1000GM PG5',
                    'product_price' => 4999,
                    'product_description' => 'GIGABYTE UD1000GM PG5，1000W 80+ Gold電源。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2022, 6, 1),
                    'product_image' => 'PSU1000G01',
                ],
                [
                    'product_name' => 'ASUS TUF Gaming 750W Bronze',
                    'product_price' => 2499,
                    'product_description' => 'ASUS TUF Gaming 750W Bronze，80+ Bronze穩定電源。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 8, 10),
                    'product_image' => 'PSU0750A01',
                ],
                [
                    'product_name' => 'MSI A650BN 650W',
                    'product_price' => 1799,
                    'product_description' => 'MSI A650BN 650W，80+ Bronze經濟型電源。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2021, 3, 1),
                    'product_image' => 'PSU0650M01',
                ],
                [
                    'product_name' => 'GIGABYTE P550B 550W',
                    'product_price' => 1499,
                    'product_description' => 'GIGABYTE P550B 550W，80+ Bronze入門級電源。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2020, 5, 15),
                    'product_image' => 'PSU0550G01',
                ],
                [
                    'product_name' => 'ASUS ROG Strix 850W Gold',
                    'product_price' => 3999,
                    'product_description' => 'ASUS ROG Strix 850W Gold，80+ Gold高效能電源。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2021, 7, 20),
                    'product_image' => 'PSU0850A02',
                ],
                [
                    'product_name' => 'MSI MPG A1000G',
                    'product_price' => 4999,
                    'product_description' => 'MSI MPG A1000G，1000W 80+ Gold模組化電源。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2022, 10, 1),
                    'product_image' => 'PSU1000M02',
                ],
                [
                    'product_name' => 'GIGABYTE AORUS P750GM',
                    'product_price' => 2999,
                    'product_description' => 'GIGABYTE AORUS P750GM，750W 80+ Gold電源。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2020, 9, 1),
                    'product_image' => 'PSU0750G02',
                ],
                [
                    'product_name' => 'ASUS TUF Gaming 1000W Gold',
                    'product_price' => 4999,
                    'product_description' => 'ASUS TUF Gaming 1000W Gold，高效能模組化電源。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2022, 11, 10),
                    'product_image' => 'PSU1000A03',
                ],
            ],
            // Category 8: 機殼 CASE
            8 => [
                [
                    'product_name' => 'ASUS TUF Gaming GT501',
                    'product_price' => 3999,
                    'product_description' => 'ASUS TUF Gaming GT501，ATX機殼，支援高效散熱。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 6, 1),
                    'product_image' => 'CASGT50101',
                ],
                [
                    'product_name' => 'MSI MPG Gungnir 110R',
                    'product_price' => 2999,
                    'product_description' => 'MSI MPG Gungnir 110R，RGB燈效ATX機殼。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2020, 10, 15),
                    'product_image' => 'CAS110R001',
                ],
                [
                    'product_name' => 'GIGABYTE C200 Glass',
                    'product_price' => 1999,
                    'product_description' => 'GIGABYTE C200 Glass，玻璃側板ATX機殼。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2019, 8, 1),
                    'product_image' => 'CASC200001',
                ],
                [
                    'product_name' => 'ASUS GR101 ROG Z11',
                    'product_price' => 4999,
                    'product_description' => 'ASUS GR101 ROG Z11，Mini-ITX旗艦機殼。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2021, 3, 10),
                    'product_image' => 'CASZ110001',
                ],
                [
                    'product_name' => 'MSI MAG Forge 100M',
                    'product_price' => 1799,
                    'product_description' => 'MSI MAG Forge 100M，經濟型ATX機殼。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2020, 2, 1),
                    'product_image' => 'CAS100M001',
                ],
                [
                    'product_name' => 'GIGABYTE AORUS C700 Glass',
                    'product_price' => 5999,
                    'product_description' => 'GIGABYTE AORUS C700 Glass，旗艦級全塔機殼。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2021, 9, 1),
                    'product_image' => 'CASC700001',
                ],
                [
                    'product_name' => 'ASUS TUF Gaming GT301',
                    'product_price' => 2499,
                    'product_description' => 'ASUS TUF Gaming GT301，RGB燈效中塔機殼。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 11, 1),
                    'product_image' => 'CASGT30101',
                ],
                [
                    'product_name' => 'MSI MPG Velox 100P',
                    'product_price' => 3499,
                    'product_description' => 'MSI MPG Velox 100P，高效散熱ATX機殼。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2021, 6, 15),
                    'product_image' => 'CAS100P001',
                ],
                [
                    'product_name' => 'GIGABYTE C301 Glass',
                    'product_price' => 2699,
                    'product_description' => 'GIGABYTE C301 Glass，時尚玻璃側板機殼。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2022, 3, 1),
                    'product_image' => 'CASC301001',
                ],
                [
                    'product_name' => 'ASUS ROG Strix Helios',
                    'product_price' => 6999,
                    'product_description' => 'ASUS ROG Strix Helios，頂級全塔RGB機殼。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 4, 1),
                    'product_image' => 'CASHELIOS0',
                ],
            ],
            // Category 9: 散熱器 COOLER
            9 => [
                [
                    'product_name' => 'ASUS ROG Ryujin II 360',
                    'product_price' => 5999,
                    'product_description' => 'ASUS ROG Ryujin II 360，360mm一體式水冷散熱器。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2021, 10, 1),
                    'product_image' => 'COL360A001',
                ],
                [
                    'product_name' => 'MSI MAG CoreLiquid 240R',
                    'product_price' => 3499,
                    'product_description' => 'MSI MAG CoreLiquid 240R，240mm水冷散熱器。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2020, 9, 15),
                    'product_image' => 'COL240M001',
                ],
                [
                    'product_name' => 'GIGABYTE AORUS Waterforce X 280',
                    'product_price' => 4999,
                    'product_description' => 'GIGABYTE AORUS Waterforce X 280，高效能水冷系統。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2021, 7, 1),
                    'product_image' => 'COL280G001',
                ],
                [
                    'product_name' => 'ASUS TUF Gaming LC 120',
                    'product_price' => 1999,
                    'product_description' => 'ASUS TUF Gaming LC 120，120mm水冷散熱器。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 6, 1),
                    'product_image' => 'COL120A001',
                ],
                [
                    'product_name' => 'MSI MAG CoreLiquid C360',
                    'product_price' => 3999,
                    'product_description' => 'MSI MAG CoreLiquid C360，360mm高效水冷。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2021, 11, 1),
                    'product_image' => 'COL360M001',
                ],
                [
                    'product_name' => 'GIGABYTE AORUS Air Cooler',
                    'product_price' => 1999,
                    'product_description' => 'GIGABYTE AORUS Air Cooler，高效能空冷散熱器。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2020, 8, 1),
                    'product_image' => 'COLAIRG001',
                ],
                [
                    'product_name' => 'ASUS ROG Strix LC 240',
                    'product_price' => 3499,
                    'product_description' => 'ASUS ROG Strix LC 240，240mm水冷散熱器。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 10, 1),
                    'product_image' => 'COL240A002',
                ],
                [
                    'product_name' => 'MSI MPG Quietude 100',
                    'product_price' => 1799,
                    'product_description' => 'MSI MPG Quietude 100，靜音空冷散熱器。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2021, 4, 1),
                    'product_image' => 'COL100M001',
                ],
                [
                    'product_name' => 'GIGABYTE AORUS Waterforce 360',
                    'product_price' => 4999,
                    'product_description' => 'GIGABYTE AORUS Waterforce 360，360mm旗艦水冷。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2021, 12, 1),
                    'product_image' => 'COL360G002',
                ],
                [
                    'product_name' => 'ASUS TUF Gaming LC 240 ARGB',
                    'product_price' => 2999,
                    'product_description' => 'ASUS TUF Gaming LC 240 ARGB，240mm RGB水冷。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2022, 3, 1),
                    'product_image' => 'COL240A003',
                ],
            ],
            // Category 10: 螢幕 MONITOR
            10 => [
                [
                    'product_name' => 'ASUS ROG Swift PG279QM',
                    'product_price' => 15999,
                    'product_description' => 'ASUS ROG Swift PG279QM，27吋2K 240Hz電競螢幕。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2021, 10, 1),
                    'product_image' => 'MON279QM01',
                ],
                [
                    'product_name' => 'MSI Optix MPG321UR-QD',
                    'product_price' => 19999,
                    'product_description' => 'MSI Optix MPG321UR-QD，32吋4K 144Hz電競螢幕。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2021, 11, 1),
                    'product_image' => 'MON321UR01',
                ],
                [
                    'product_name' => 'GIGABYTE M27Q X',
                    'product_price' => 12999,
                    'product_description' => 'GIGABYTE M27Q X，27吋2K 240Hz電競螢幕。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2022, 2, 1),
                    'product_image' => 'MONM27QX01',
                ],
                [
                    'product_name' => 'ASUS TUF Gaming VG28UQL1A',
                    'product_price' => 17999,
                    'product_description' => 'ASUS TUF Gaming VG28UQL1A，28吋4K 144Hz螢幕。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2021, 8, 1),
                    'product_image' => 'MON28UQL01',
                ],
                [
                    'product_name' => 'MSI Optix G241',
                    'product_price' => 5999,
                    'product_description' => 'MSI Optix G241，24吋1080p 144Hz電競螢幕。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2020, 6, 1),
                    'product_image' => 'MONG241001',
                ],
                [
                    'product_name' => 'GIGABYTE G27F 2',
                    'product_price' => 6999,
                    'product_description' => 'GIGABYTE G27F 2，27吋1080p 165Hz電競螢幕。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2022, 4, 1),
                    'product_image' => 'MONG27F201',
                ],
                [
                    'product_name' => 'ASUS ProArt PA279CV',
                    'product_price' => 11999,
                    'product_description' => 'ASUS ProArt PA279CV，27吋4K專業創作螢幕。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 9, 1),
                    'product_image' => 'MONPA27901',
                ],
                [
                    'product_name' => 'MSI Creator PS321QR',
                    'product_price' => 14999,
                    'product_description' => 'MSI Creator PS321QR，32吋2K創作者專用螢幕。',
                    'supplier_id' => 2,
                    'launch_date' => Carbon::create(2021, 5, 1),
                    'product_image' => 'MONPS32101',
                ],
                [
                    'product_name' => 'GIGABYTE AORUS FI32U',
                    'product_price' => 18999,
                    'product_description' => 'GIGABYTE AORUS FI32U，32吋4K 144Hz電競螢幕。',
                    'supplier_id' => 3,
                    'launch_date' => Carbon::create(2021, 7, 1),
                    'product_image' => 'MONFI32U01',
                ],
                [
                    'product_name' => 'ASUS VG259QM',
                    'product_price' => 7999,
                    'product_description' => 'ASUS VG259QM，25吋1080p 280Hz電競螢幕。',
                    'supplier_id' => 1,
                    'launch_date' => Carbon::create(2020, 11, 1),
                    'product_image' => 'MON259QM01',
                ],
            ],
        ];

        // Insert products into the database
        foreach ($products as $category_id => $category_products) {
            foreach ($category_products as $product) {
                Product::create([
                    'product_name' => $product['product_name'],
                    'product_price' => $product['product_price'],
                    'product_description' => $product['product_description'],
                    'category_id' => $category_id,
                    'supplier_id' => $product['supplier_id'],
                    'product_image' => $product['product_image'],
                    'launch_date' => $product['launch_date'],
                    'launch_status' => 'active',
                ]);
            }
        }
    }
}
